[package]
name = "booter"
version = "0.1.0"
edition = "2021"
default-run = "booter"

[dependencies]
fatfs = "0.3.6"
fscommon = "0.1.1"
ovmf-prebuilt = "0.1.0-alpha.1"

clap = { version = "4.5.1", features = ["derive"] }
